server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.simulator.url=http://localhost:8080

# Actuator
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%X{paymentId}] %logger{36} - %msg%n
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.status.order=DOWN,DEGRADED,UP
management.endpoint.health.status.http-mapping.degraded=200
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=Payment Gateway
info.app.description=REST API for processing card payments via an acquiring bank