server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.simulator.url=http://localhost:8080

# Actuator
management.endpoint.health.show-details=always
management.endpoint.health.status.order=DOWN,OUT_OF_SERVICE,DEGRADED,UNKNOWN,UP
management.endpoint.health.status.http-mapping.degraded=200